### ISSUE TITLE
permission problems

### ISSUE THREAD

**Issue by antonkulaga** [jodersky/flow#18]
I develop a GUI for openhardware spectophotometer ( https://github.com/antonkulaga/di-lambda ) and I use flow to connect to it via USB serial port. I experience a lot of problems. 
The most unpleasant one is a permission problem. Linux users have to add themselves to special groups to be able to access the serial port. And even after addition some errors occur, for instance when you pluged in the device and then suddengly pluged it out then after pluging it back you will have a permission problem even if you already added yourself to right groups. And sometimes such permission problems appear even when I restarted the app (probably native lib part of the flow is still active)

**Comment by jodersky** [comment]
Your project looks very cool!

Regarding the permission problems, I am almost certain this is not a flow issue but rather a general Linux, udev configuration issue. 

This is because flow's backend uses only standard posix functions to communicate with connected devices; it is not a kernel module that detects or creates device nodes. Therefore, flow as well as almost any library that deals with any devices of any kind (in any language), relies on Linux's device manager `udev` to detect devices and create associated nodes. By default, any serial device (also serial over USB) that is plugged in is associated an `/dev/ttyX` node with owners `root:dialout` and permissions 0660.
Such behavior can be changed with so called udev "rules", for example the rule

```
SUBSYSTEMS=="usb", ATTRS{idProduct}=="XXXX", ATTRS{idVendor}=="YYYY", GROUP="users", MODE="0666" SYMLINK+="arduino%n" 
```

will create device nodes called `/dev/arduinoX` for any usb device with product id XXXX and vendor id YYYY, owned by group "users" and writeable by everyone.

Udev rules are stored in `/etc/udev/rules.d/`.

I would suggest to search on how to create udev rules for your device, that way you can then rely on specific names and assigned permissions.

**Comment by antonkulaga** [comment]
I think that permission problems should be described in docs. I chose flow because it looks rather simple (if I had good knowledge of C++ I would write the native part myself).
I suspect that in most of the cases flow users wil use https://github.com/sbt/sbt-native-packager to make installers, so having recipes for it (like changing udev rules for linux packaging) in docs can be useful

**Comment by jodersky** [comment]
There is one very hidden place in the docs that says Linux users need to be in the `dialout` group. However I agree with you that it should be made more explicit, along with a mention of udev. Maybe even a troubleshooting/FAQ guide could be useful.

Regarding your intermittent permission problems, have you noticed any patterns to their appearance, e.g. only when you disconnect and reconnect really quickly? Do they persist if you run your app as root (this should not be a durable solution, just a way to narrow down potential causes)?
